[[documents]]
name = "2023-04-08-easterhegg"
video = "https://media.ccc.de/v/eh20-4-rosenpass-ein-vpn-zum-schutz-vor-quantencomputern"

[[documents]]
name = "2023-07-04-IAV"

[[documents]]
name = "2023-07-10-FormosaRetreat"

[[documents]]
name = "2023-09-03-MRMCD2023"

[[documents]]
name = "2024-03-01-ptfDemoDay"

[[documents]]
name = "2024-08-29-hackmas"

[[documents]]
name = "2024-09-20-eacn"
