$pdf_mode=4;
$lualatex = 'lualatex -shell-escape';

 ensure_path('TEXINPUTS','../tex//');
 ensure_path('LUAINPUTS','../tex//');
 ensure_path('OSFONTDIR', '../tex//');

@default_files=("*slides*.tex");
